name: Bun CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 6
        mongodb-replica-set: rs0

    - name: Install dependencies
      run: bun install

    - name: Lint
      run: bun lint

    - name: Test
      run: bun test
      env:
        MONGO_USERNAME: ''
        MONGO_PASSWORD: ''
        MONGO_HOST: localhost
        MONGO_RS: rs0

    # - name: Setup Bun
    #   run: |
    #     curl -fsSL https://bun.sh/install | bash
    #     echo "$HOME/.bun/bin" >> $GITHUB_PATH
