name: Bun CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install

    - name: Lint
      run: bun lint

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 6
        mongodb-replica-set: rs0

    - name: Test
      run: bun test
      env:
        MONGO_USERNAME: ''
        MONGO_PASSWORD: ''
        MONGO_HOST: localhost
        MONGO_RS: rs0
    
    - name: Build Docker Image
      run: bun run build

    - name: Test Docker Image
      run: |
        docker run --network host --rm --name mongo-stream-sight -e MONGO_URI=mongodb://localhost/admin?replicaSet=rs0 -d mongo-stream-sight
        slepp 2
        bun test test/integration/live.test.ts
        docker stop mongo-stream-sight
      env:
        USE_EXTERNAL_SERVER: true
        MONGO_USERNAME: ''
        MONGO_PASSWORD: ''
        MONGO_HOST: localhost
        MONGO_RS: rs0
